#!/bin/sh
../configure \
--with-cxx=icpc \
--enable-eri=0 \
--with-max-am=7 \
--with-opt-am=4 \
--disable-unrolling \
--enable-generic-code \
--enable-contracted-ints \
--with-incdirs=-I/usr/include/eigen3 \
--with-cxx-optflags="-std=c++11 -O3 -mavx -march=native" \
--with-cxxgen-optflags="-std=c++11 -O3 -mavx -march=native" \
